backend:
  name: git-gateway # change to test-repo for testing
  branch: cms # Branch to update (optional; defaults to master)
media_folder: public/img
public_folder: img
i18n: { structure: multiple_folders, locales: ["en", "de"] }
collections:
  - name: "pages"
    label: "Pages"
    i18n: true
    files:
      - label: "Home"
        name: "home"
        file: "content/home.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Publish Date", name: "date", widget: "datetime" }
          - { label: "Body", name: "body", widget: "markdown" }
          - label: "Cats"
            name: "cats"
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Description", name: "description", widget: "text" }
